### ISSUE TITLE
Questions about the ensembling

### ISSUE THREAD

**Issue by Cogito2012** [sgvaze/osr_closed_set_all_you_need#13]
Hi,

Thank you for sharing this great work! I'd like to know what are the configurations of the ensemble of models.

In the paper and supplementary, they only mentioned it "by bootstrapping the training data and training K = 5 ensembles." And in this code repo (line [151](https://github.com/sgvaze/osr_closed_set_all_you_need/blob/dcc9c3bead7bd828db546bcdf88ae84ce298d6c7/methods/tests/openset_test.py#L151) and line [183](https://github.com/sgvaze/osr_closed_set_all_you_need/blob/dcc9c3bead7bd828db546bcdf88ae84ce298d6c7/methods/tests/openset_test.py#L183)), it seems that for each of the 5 dataset splits, only a single model is used? 

This is confusing because in line [183](https://github.com/sgvaze/osr_closed_set_all_you_need/blob/dcc9c3bead7bd828db546bcdf88ae84ce298d6c7/methods/tests/openset_test.py#L183), it uses `split_idx` as the index of `all_paths_combined`, which is a list of models from 5 experiments `exp_ids`. So do you mean each exp_id corresponds to a single model trained from one dataset split? Correct me if I misunderstood this part.

Looking forward to your reply.
Thank you!

**Comment by sgvaze** [comment]
Hello, thanks for your interest in our work! 

Yes, you are correct, this part of the code was originally written for evaluating with ensembles. However, since then we have only evaluated with single models.

As you said, the `split_idx` refers to the set of open/closed-set classes. Let me know if this answers your question!
